# Generated by Django 3.2.5 on 2021-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image_file', models.ImageField(help_text='이미지 사이즈에 따라 화면에 상이하게 보일 수 있기 때문에 업로드 및 수정 후 화면 확인이 필요합니다.', upload_to='banner/', verbose_name='베너 이미지')),
                ('mobile_image_file', models.ImageField(help_text='이미지 사이즈에 따라 화면에 상이하게 보일 수 있기 때문에 업로드 및 수정 후 화면 확인이 필요합니다.', null=True, upload_to='banner/', verbose_name='모바일_베너 이미지')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='타이틀')),
                ('content', models.TextField(null=True, verbose_name='베너 내용')),
                ('sort', models.IntegerField(default=1, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name_plural': '메인베너 관리',
            },
        ),
    ]
