# Generated by Django 3.2.5 on 2021-07-27 18:10

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('type', models.CharField(choices=[('A.일반', 'A.일반'), ('B.유형1', 'B.유형1'), ('C.유형2', 'C.유형2'), ('D.유형3', 'D.유형3')], default='일반', max_length=20, verbose_name='유형')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '자주묻는 질문 관리',
            },
        ),
        migrations.CreateModel(
            name='DirectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='처리완료')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('answer_file', models.FileField(blank=True, help_text='질문 응답에 필요한 첨부파일 입니다.', null=True, upload_to='question/', verbose_name='답변 보조자료')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '1:1 문의',
            },
        ),
    ]
