# Generated by Django 3.2.5 on 2021-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제작의뢰명')),
                ('company', models.CharField(max_length=100, verbose_name='상 호')),
                ('name', models.CharField(max_length=20, verbose_name='성 명')),
                ('password', models.CharField(help_text='비밀번호는 의뢰 삭제 시 필요합니다.', max_length=4, verbose_name='비밀번호')),
                ('tel', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('pro_type', models.CharField(choices=[('패키지', '패키지'), ('쇼핑백', '쇼핑백'), ('형택', '형택'), ('기타제작물', '기타제작물')], default='패키지', max_length=20, verbose_name='제작물')),
                ('pro_qny', models.IntegerField(verbose_name='제작수량')),
                ('size_width', models.IntegerField(verbose_name='사이즈 가로(mm)')),
                ('size_length', models.IntegerField(verbose_name='사이즈 세로(mm)')),
                ('size_height', models.IntegerField(verbose_name='사이즈 높이(mm)')),
                ('design_yn', models.CharField(choices=[('없음', '없음'), ('의뢰', '의뢰')], default='없음', max_length=30, verbose_name='디자인 유/무')),
                ('paper_type', models.CharField(choices=[('아트지', '아트지'), ('스노우화이트', '스노우화이트'), ('SC마니라', 'SC마니라'), ('로얄아이보리', '로얄아이보리'), ('기타재질', '기타재질')], default='아트지', max_length=50, verbose_name='종이재질')),
                ('print_spec', models.CharField(choices=[('없음', '없음'), ('4도 컬러인쇄', '4도 컬러인쇄'), ('1도 단색인쇄', '1도 단색인쇄'), ('별색인쇄', '별색인쇄'), ('UV인쇄', 'UV인쇄'), ('기타인쇄', '기타인쇄')], default='없음', max_length=30, verbose_name='인쇄사양')),
                ('coating', models.CharField(choices=[('없음', '없음'), ('무광라미네이팅', '무광라미네이팅'), ('유광라미네이팅', '유광라미네이팅')], default='없음', max_length=30, verbose_name='코 팅')),
                ('processing', models.CharField(max_length=50, verbose_name='후가공')),
                ('content', models.TextField(verbose_name='문의내용')),
                ('is_completed', models.BooleanField(default=False, help_text='처리가 완료 된 주문은 꼭 체크 해주세요.', verbose_name='처리현황')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='order/', verbose_name='첨부파일1')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='order/', verbose_name='첨부파일2')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='order/', verbose_name='첨부파일3')),
            ],
            options={
                'verbose_name_plural': '주문의뢰 관리',
            },
        ),
    ]
