# Generated by Django 3.2.5 on 2021-07-27 18:10

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('thumbnail', models.ImageField(default='https://via.placeholder.com/300x300/ffffff?text=300x300', help_text='썸네일은 필수 입니다. 사이즈는 px을 기준으로 하며 300 x 300 입니다.', upload_to='event/', verbose_name='썸네일')),
                ('title', models.CharField(default='제목없음', max_length=200, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hit', models.IntegerField(default=0, verbose_name='조회수')),
                ('event_start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('event_end_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': '이벤트 관리',
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hit', models.IntegerField(default=0, verbose_name='조회수')),
                ('asdflkasdklf', models.CharField(max_length=30, null=True)),
                ('asdflkasdklf22', models.CharField(max_length=30, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name_plural': '공지사항 관리',
            },
        ),
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='boardfiles/')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boardapp.noticeboard')),
            ],
        ),
    ]
