# Generated by Django 3.2.5 on 2021-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': '약관내용 관리',
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(help_text='푸터에 보일 정보 중 제목 입니다.', max_length=120, verbose_name='제목')),
                ('content', models.CharField(help_text='푸터에 보일 정보 중 내용 입니다.', max_length=350, verbose_name='내용')),
            ],
            options={
                'verbose_name_plural': '하단정보 관리',
            },
        ),
        migrations.CreateModel(
            name='LogoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(help_text='푸터에 보일 정보 중 제목 입니다.', max_length=120, verbose_name='제목')),
                ('logo_file', models.ImageField(help_text='사이즈에 따라 상이하게 보일 수 있습니다. 업로드 후 화면에서 확인이 필요합니다.', upload_to='logo/', verbose_name='로고파일')),
            ],
            options={
                'verbose_name_plural': '로고정보 관리',
            },
        ),
    ]
