# Generated by Django 3.2.5 on 2021-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_footerinfo_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='정렬순서'),
        ),
    ]
