# Generated by Django 3.2.5 on 2021-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.IntegerField(help_text='정렬 순서는 3자리 까지 입력 가능합니다.', verbose_name='정렬 순서'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort',
            field=models.IntegerField(help_text='정렬 순서는 3자리 까지 입력 가능합니다.', verbose_name='정렬 순서'),
        ),
    ]
