# Generated by Django 3.2.5 on 2021-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20210728_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spec',
            field=models.TextField(blank=True, help_text='행택의 유형을 선택한 경우에만 적용됩니다.', null=True, verbose_name='제작 사양'),
        ),
    ]
