# Generated by Django 3.2.5 on 2021-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_product_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '상품/제품 관리'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
