# Generated by Django 3.2.5 on 2021-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_product_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(help_text='화면에 줄바꿈이 필요한 경우 Enter대신 br 테그를 입력해주세요.', verbose_name='상품 내용'),
        ),
    ]
