# Generated by Django 3.2.5 on 2021-08-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_alter_product_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(help_text='화면에 줄바꿈이 필요한 경우 Enter대신 br 태그를 입력해주세요.', verbose_name='상품 내용'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec',
            field=models.TextField(blank=True, help_text='행택의 유형을 선택한 경우에만 적용됩니다. 화면에 줄바꿈이 필요한 경우 Enter대신 br 태그를 입력해주세요.', null=True, verbose_name='제작 사양'),
        ),
    ]
